services:
  frontend:
    build: 
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - SERVER_URL=http://0.0.0.0:8000/todo/
    ports:
      - 3000:3000 
    command: sh -c "npm run build &&
                    node ./.output/server/index.mjs"              
                     
  backend:
    build: 
      context: ./backend
    depends_on: 
      - db  
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
    
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    uwsgi --http :8000 --master --enable-threads --module server.wsgi"

  db:
    image: postgres:12.17-alpine
    expose:
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - PGPORT=${POSTGRES_PORT}
