services:
  frontend:
    build: 
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    command: sh -c "npm run build &&
                    node ./.output/server/index.mjs"
    # expose:
    #   - 3000:3000                        


  backend:
    build: 
      context: ./backend
    depends_on: 
      - db  
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
      # - 35729:35729    
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8000 server.wsgi"
    # expose:
    #   - 8000:8000     


  db:
    image: postgres:12.17-alpine
    # env_file:
    #   - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - PGPORT=${POSTGRES_PORT}