services:
  todo-app:
    build:
      context: ./
    depends_on:
      - todo-database
    env_file:
      - .env
    environment:
      -   POSTGRES_HOST=todo-database
    ports:
      - 8000:8000
      - 35729:35729

    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8000 server.wsgi"
                       
    expose:
      - 8000:8000  


  todo-database:
    image: postgres:12.17-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - PGPORT=${POSTGRES_PORT}
