FROM python:3.9.18-slim

RUN mkdir -p /app

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# COPY requirements.txt ./

COPY . .

RUN pip install --upgrade pip  

RUN pip install -r requirements.txt 

# RUN python manage.py makemigrations

# RUN python manage.py migrate

CMD [ "python", "manage.py", "runserver" ]

EXPOSE 8000


